- name: install apache
  yum:
    name: httpd
    state: present

- name: start httpd
  service:
    name: httpd
    state: started

- name: copy index.html
  template:
    src: index.j2
    dest: /var/www/html/index.html

- name: example copying file with owner and permissions
  copy:
    src: /srv/myfiles/foo.conf
    dest: /etc/foo.conf
    owner: foo
    group: foo
    mode: 0644    
