---

- name: prepare base systems
  hosts: all
  become: true

  roles:
  - common
    
- name: deploy flask infrastructure
  hosts: flasks
  gather_facts: false
  become: true

  tasks:

  - name: placeholder for flask
    debug:
      msg: flask config starts here

- name: deploy postgres 
  hosts: databases
  gather_facts: false
  become: true

  tasks:

  - name: placeholder for flask
    debug:
      msg: postgres config starts here

  roles:
  - {name: geerlingguy.postgresql, tags: [postgres]}
