- name: create student webpage
  template:
    src: ./templates/intro.md.j2
    dest: "{{ playbook_dir }}/{{ ec2_name_prefix }}/website/intro.md"
  tags: intro

- name: copy network.html over
  copy:
    src: ./templates/network.html
    dest: "{{ playbook_dir }}/{{ ec2_name_prefix }}/website/network.html"
  tags: intro
