- name: import contrl node playbook
  hosts: control_nodes
  become: true
  gather_facts: false

  vars:
    - flask_repo: https://github.com/tonykay/flask-ansible-lab.git
    - solution_repo: https://github.com/tonykay/rhte-networking-solution.git
    - app_name: flask-app 
    - packages:
      - python-pip
      - postgresql
      - git

  tasks:

  - name: additional base packages
    package:
      name: "{{ item }}"
      state: present
    loop: "{{ packages }}" 

    #  - name: clone flask source code`
    #    git:
    #      repo: "{{ flask_repo }}"
    #      dest: "/opt/{{ app_name }}"
    #      update: yes  

  - name: clone solution into user directory
    git:
      repo: "{{ solution_repo }}"
      dest: "/home/{{ username  }}/rhte-networking-solution"
      update: yes  

  - name: give user ownership of repo
    file:
      path: "/home/{{ username  }}/rhte-networking-solution"
      owner: "{{ username }}"
      group: "{{ username }}"
      recurse: true

  - name: remove users ansible.cfg
    file:
      path: "/home/{{ username }}/.ansible.cfg"
      state: absent

  - name: hack the banners
    command: "ansible-playbook /home/{{ username }}/rhte-networking-solution/banner/banner.yml"


      #- name: install flask application requirements
      #pip:
      #requirements: "/opt/{{ app_name }}/requirements.txt"

  - name: output student login message    
    debug:
      msg: "user.info: {{ username }}@{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"

  roles:
    - haproxy    
