- name: import lab_hosts playbook
  hosts: lab_hosts
  become: yes
  gather_facts: false

  tasks:

  - name: placeholder for postgres
    debug:
      msg: postgres config starts here

  - name: copy over webserver images
    copy:
      src: files/seagull.png 
      dest: /var/www/html/
      mode: 0644

  roles:

  - { name: webservers, tags: [webservers] }
    #  - {name: geerlingguy.postgresql, tags: [postgres]}
